project:
  type: website
  output-dir: docs  # Cam
  
 
website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: EDA
      - href: act.qmd
        text: Laboratorio 1
      - href: classification.qmd
        text: Classification
      - href: midreg.qmd
        text: MidReg
      - href: midcla.qmd
        text: MidCla        
 
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged