project:
  type: website
  output-dir: docs
  preview:
    watch-inputs: true   # <- recarga al guardar
website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: LAB2.qmd
        text: Laboratorio 2
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
