project:
  type: website

website:
  title: "Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: midcla.qmd
        text: MidCla
      - href: midreg.qmd
        text: MidReg
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged
